### ISSUE TITLE
Create Your first - SSH //RSA /

### ISSUE THREAD

**Issue by 47AD0** [microsoft/microsoft-ui-xaml#9293]
[http://localhost:8158/10.10.10.150](http://10.10.10.150:8088/system/webdev/MyProject/newfile.html)<h6><details><summary>
```
namespace: 
     
                job:

    workflow:

            code:

     ghpages:


```

</summary>
<p> 
<h1> 47ADO </h1>
<h2> "job" : "issues" </h2>
<h2> "workflow" : "install/codespaces/ghpages/codes" </h2>
<h2> "code" : "enviroment" </h2>
<h2> "ghpages" : "http://system/webdev/Myproject/Newfile.html" </h2> 
</p>
</details>
</h6>
